apiVersion: v1
items:
- apiVersion: v1
  data:
    database-name: "{{ .Values.database.name }}"
    database-password: "{{ .Values.database.password }}"
    database-root-password: "{{ .Values.database.rootPassword }}"
    database-user: "{{ .Values.database.user }}"
  kind: Secret
  metadata:
    labels:
      app: wordpress
      tier: mariadb
    name: wordpress-mariadb
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
