apiVersion: v1
items:
- apiVersion: v1
  data:
    database-name: d29yZHByZXNzZGI=
    database-password: d29yZHByZXNz
    database-root-password: d29yZHByZXNzLWFkbWlu
    database-user: d29yZHByZXNz
  kind: Secret
  metadata:
    labels:
      app: wordpress
      tier: mariadb
    name: wordpress-mariadb
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
