apiVersion: v1
items:
- apiVersion: v1
  data:
    DATABASE_SERVICE_NAME: d29yZHByZXNzLW1hcmlhZGI=
    MARIADB_VERSION: MTAuMy1lbDg=
    MEMORY_LIMIT: NTEyTWk=
    MYSQL_DATABASE: d29yZHByZXNzZGI=
    MYSQL_PASSWORD: d29yZHByZXNz
    MYSQL_ROOT_PASSWORD: d29yZHByZXNzLWFkbWlu
    MYSQL_USER: d29yZHByZXNz
    NAMESPACE: b3BlbnNoaWZ0
  kind: Secret
  metadata:
    generateName: mariadb-ephemeral-parameters-
    labels:
      app: wordpress
      tier: mariadb
    name: mariadb-ephemeral-parameters-hz5xg
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
