---
apiVersion: v1
data:
  COMPONENT_INVENTORY_HOST: aW52ZW50b3J5LWNvb2xzdG9yZQ==
  COMPONENT_INVENTORY_PORT: ODA4MA==
kind: Secret
metadata:
  annotations:
    component-port: "8080"
  labels:
    app: coolstore
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime-version: "11"
  name: inventory-coolstore-8080
type: Opaque
---
apiVersion: v1
data:
  COMPONENT_INVENTORY_HOST: aW52ZW50b3J5LWNvb2xzdG9yZQ==
  COMPONENT_INVENTORY_PORT: ODQ0Mw==
kind: Secret
metadata:
  annotations:
    component-port: "8443"
  labels:
    app: coolstore
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime-version: "11"
  name: inventory-coolstore-8443
type: Opaque
---
apiVersion: v1
data:
  COMPONENT_INVENTORY_HOST: aW52ZW50b3J5LWNvb2xzdG9yZQ==
  COMPONENT_INVENTORY_PORT: ODc3OA==
kind: Secret
metadata:
  annotations:
    component-port: "8778"
  labels:
    app: coolstore
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime-version: "11"
  name: inventory-coolstore-8778
type: Opaque
