# Default values for cloud-native-java.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

type: ""

replicaCount: 1

image:
  repository: quay.io/mcouliba/quarkus-serverless
  tag: "1.0"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# probes:
#   liveness:
#     path: /
#   readiness:
#     path:  /