apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    labels:
      app: backend
      app.kubernetes.io/instance: backend
      pipeline.openshift.io/runtime: java
      pipeline.openshift.io/type: kubernetes
    name: backend
  spec:
    params:
    - default: backend
      name: APP_NAME
      type: string
    - default: https://github.com/Red-Wine-Software/backend
      name: GIT_REPO
      type: string
    - default: summit2021
      name: GIT_REVISION
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/backend
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: $(params.GIT_REPO)
      - name: revision
        value: $(params.GIT_REVISION)
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: workspace
    - name: build
      params:
      - name: IMAGE
        value: $(params.IMAGE_NAME)
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: $(params.PATH_CONTEXT)
      runAfter:
      - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java-11
      workspaces:
      - name: source
        workspace: workspace
    - name: deploy
      params:
      - name: SCRIPT
        value: kubectl $@
      - name: ARGS
        value:
        - rollout
        - status
        - deploy/$(params.APP_NAME)
      runAfter:
      - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    workspaces:
    - name: workspace
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
